package com.m57.hermescontrol.theme.presets

import androidx.compose.ui.graphics.Color
import com.m57.hermescontrol.theme.HermesStatusColors
import com.m57.hermescontrol.theme.PaletteColors
import com.m57.hermescontrol.theme.buildTheme

/** Brand default theme — voltage purple primary, plasma amber secondary. */
val DefaultTheme =
    buildTheme(
        dark =
            PaletteColors(
                primary = Color(0xFF7C5CFF),
                onPrimary = Color(0xFFFFFFFF),
                primaryContainer = Color(0xFF2B2159),
                onPrimaryContainer = Color(0xFFD9CCFF),
                secondary = Color(0xFFFFB627),
                onSecondary = Color(0xFF000000),
                secondaryContainer = Color(0xFF3D2F0F),
                onSecondaryContainer = Color(0xFFFFE082),
                tertiary = Color(0xFFFFE082),
                onTertiary = Color(0xFF000000),
                tertiaryContainer = Color(0xFF3D2F0F),
                onTertiaryContainer = Color(0xFFFFE082),
                background = Color(0xFF0B0B11),
                onBackground = Color(0xFFE8E6EE),
                surface = Color(0xFF121218),
                onSurface = Color(0xFFE8E6EE),
                surfaceVariant = Color(0xFF1C1C26),
                onSurfaceVariant = Color(0xFFB6B2C4),
                surfaceContainerLowest = Color(0xFF07070C),
                surfaceContainerLow = Color(0xFF0F0F14),
                surfaceContainer = Color(0xFF1C1C26),
                surfaceContainerHigh = Color(0xFF262633),
                surfaceContainerHighest = Color(0xFF30303D),
                inverseSurface = Color(0xFFE8E6EE),
                inverseOnSurface = Color(0xFF1A1A24),
                inversePrimary = Color(0xFF5A3FE0),
                outline = Color(0xFF4A4A5A),
                outlineVariant = Color(0xFF2F2F3D),
                scrim = Color(0xFF000000),
                status =
                    HermesStatusColors(
                        success = Color(0xFF3DDC84),
                        successContainer = Color(0xFF143A23),
                        onSuccess = Color(0xFFF5F5F5),
                        warning = Color(0xFFFFB627),
                        warningContainer = Color(0xFF3D2F0F),
                        onWarning = Color(0xFFF5F5F5),
                        error = Color(0xFFFF5C5C),
                        errorContainer = Color(0xFF3D1414),
                        onError = Color(0xFFFFFFFF),
                        onErrorContainer = Color(0xFFFFB4B4),
                        info = Color(0xFF4DA8FF),
                        infoContainer = Color(0xFF0F2A3D),
                        onInfo = Color(0xFFF5F5F5),
                    ),
            ),
        light =
            PaletteColors(
                primary = Color(0xFF5A3FE0),
                onPrimary = Color(0xFFFFFFFF),
                primaryContainer = Color(0xFFAC93FF),
                onPrimaryContainer = Color(0xFF1E0F66),
                secondary = Color(0xFFC68400),
                onSecondary = Color(0xFFFFFFFF),
                secondaryContainer = Color(0xFFFFE082),
                onSecondaryContainer = Color(0xFF3D2F0F),
                tertiary = Color(0xFFC68400),
                onTertiary = Color(0xFFFFFFFF),
                tertiaryContainer = Color(0xFFFFE082),
                onTertiaryContainer = Color(0xFF3D2F0F),
                background = Color(0xFFF7F6FB),
                onBackground = Color(0xFF1A1A24),
                surface = Color(0xFFFFFFFF),
                onSurface = Color(0xFF1A1A24),
                surfaceVariant = Color(0xFFEFEDF4),
                onSurfaceVariant = Color(0xFF56536A),
                surfaceContainerLowest = Color(0xFFFFFFFF),
                surfaceContainerLow = Color(0xFFF3F1F8),
                surfaceContainer = Color(0xFFEFEDF4),
                surfaceContainerHigh = Color(0xFFE6E3EE),
                surfaceContainerHighest = Color(0xFFDDD9EA),
                inverseSurface = Color(0xFF1A1A24),
                inverseOnSurface = Color(0xFFE8E6EE),
                inversePrimary = Color(0xFFAC93FF),
                outline = Color(0xFF79748E),
                outlineVariant = Color(0xFFC9C5D6),
                scrim = Color(0xFF000000),
                status =
                    HermesStatusColors(
                        success = Color(0xFF1B873A),
                        successContainer = Color(0xFFD7F5E0),
                        onSuccess = Color(0xFFFDF8FF),
                        warning = Color(0xFFC68400),
                        warningContainer = Color(0xFFFFEAB3),
                        onWarning = Color(0xFFFDF8FF),
                        error = Color(0xFFB3261E),
                        errorContainer = Color(0xFFF9DEDC),
                        onError = Color(0xFFFDF8FF),
                        onErrorContainer = Color(0xFF410E0B),
                        info = Color(0xFF2E6FBD),
                        infoContainer = Color(0xFFD4E7FF),
                        onInfo = Color(0xFFFDF8FF),
                    ),
            ),
    )
